[package]
name = "rust_read_font"
version = "0.1.0"
edition = "2018"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
memmap = "0.7.0"
zerocopy = "0.5.0"
byteorder = "1.4.3"